config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here

  patch 'line_items/update/:id' => 'line_items#update', :as => 'line_items_update'

  resources :paxes

  namespace :admin do
    resources :product_types
    resources :products do
      resources :rates
      member do
        post :delete_rates
      end
    end
  end

  namespace :api, defaults: { format: 'json' } do
    resources :paxes
  end

end

app/models/spree/rate.rb
# frozen_string_literal: true

# TODO: relate this model with Spree::Price for having multicurrency support
module Spree
  class Rate < Spree::Base
    include Spree::PersistedDynamicAttribute

    def self.excluded_list
      ['variant_id', 'variant=']
    end

    belongs_to :variant,
               class_name: 'Spree::Variant',
               foreign_key: 'variant_id'
    has_many :rate_option_values,
             class_name: 'Spree::RateOptionValue',
             foreign_key: 'rate_id',
             dependent: :delete_all
    has_many :line_items, class_name: 'Spree::LineItem'

    validates_presence_of :rate_option_values

    def find_existing_option_value(option_type)
      rate_option_values
        .joins(:option_value)
        .where('spree_option_values.option_type_id = ?', option_type.id)
        .take
    end
  end
end

app/controllers/spree/admin/rates_controller.rb
# frozen_string_literal: true

module Spree
  module Admin
    class RatesController < ResourceController
      before_action :load_product

      def load_product
        @product = Spree::Product.find_by(slug: params[:product_id])
      end

      def index
        @product_type_name          = @product.product_type.name
        @product_option_types       = @product.option_types
        @product_rate_option_types  = @product.rate_option_types
        @product_rates              = @product.rates
                                              .includes(:rate_option_values, variant: [option_values: :option_type])
      end

      def collection_url
        admin_product_rates_path
      end

      def edit_object_url(rate)
        edit_admin_product_rate_path(product_id: rate.variant.product.slug, id: rate.id)
      end

      def object_url(rate)
        admin_product_rate_path(product_id: rate.variant.product.slug, id: rate.id)
      end

      def create
        @rate = Spree::Rate.new(variant_id: params[:rate][:variant_id])
        params[:product_type] = @product.product_type.name

        if save_rate
          flash[:success] = flash_message_for(@rate, :successfully_created)
          redirect_to admin_product_rates_path(params[:product_id])
        else
          flash[:error] = 'There was a problem creating the rate'
          respond_with(@rate) do |format|
            format.html { render action: :new }
            format.js { render layout: false }
          end
        end
      end

      def update
        @rate = Spree::Rate.find(params[:id])
        params[:product_type] = @product.product_type.name

        if save_rate
          flash[:success] = flash_message_for(@rate, :successfully_updated)
          redirect_to admin_product_rates_path(params[:product_id])
        else
          invoke_callbacks(:update, :fails)
        end
      end

      private

      def save_rate
        ApplicationRecord.transaction do
          @rate.persist_option_values(params_sanitize)
          @rate.save!
        end
      rescue StandardError
        false
      end

      def params_sanitize
        Spree::ParamsSanitize.new(klass: 'rate', params: params).call
      end
    end
  end
end

app/views/spree/admin/rates/_form.html.erb
<div data-hook="admin_product_rates_form_fields" class="col-md-12">
  <div class="form-group field">
     <%= label_tag :variant, Spree.t(:variant) %>
     <%= select_tag 'rate[variant_id]', options_for_select(@product.variants.map { |v| [v.sku, v.id] }, @rate.variant_id), class: 'select2 fullwidth' %>
  </div>
  <% prefix = "#{@product.product_type.name}_" %>
  <% @product.rate_option_types.each do |ot| %>
  <div class="form-group field">
    <%= label_tag prefix + ot.name, raw(Spree.t(ot.name) + content_tag(:span, ' *', class: 'required'))%>
    <% current_value = @rate.persisted_option_value(ot) %>
      <% if ot.attr_type == 'selection' %>
        <%= select_tag "rate[#{prefix}#{ot.name}]", options_for_select(ot.option_values.map { |ov| [ov.presentation, ov.id] }, current_value), class: 'select2 fullwidth',  required: true%>
      <% elsif ot.attr_type == 'integer' %>
        <%= number_field_tag "rate[#{prefix}#{ot.name}]", current_value, class: 'form-control', min: 0, required: true %>
      <% elsif ot.attr_type == 'float' %>
        <%= number_field_tag "rate[#{prefix}#{ot.name}]", current_value, class: 'form-control' , min: 0, required: true%>
      <% elsif ot.attr_type == 'boolean' %>
        <%= check_box_tag "rate[#{prefix}#{ot.name}]", 1 %>
      <% elsif ot.attr_type == 'date' %>
        <%= text_field_tag "rate[#{prefix}#{ot.name}]", current_value, class: 'datepicker form-control', required: true%>
      <% else %>
        <%= text_field_tag "rate[#{prefix}#{ot.name}]", current_value, class: 'fullwidth form-control', required: true %>
      <% end %>
   </div>
  <% end %>
</div>

app/views/spree/admin/rates/edit.html.erb
<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => 'Product Rate'} %>

<% content_for :page_title do %>
  <%= Spree.t(:edit_rate) %>
<% end %>

<% content_for :page_actions do %>
  <%= link_to_with_icon 'arrow-left',
                        Spree.t(:back_to_resource_list,
                        resource: Spree::Rate.model_name.human),
                        admin_product_rates_path,
                        class: 'btn btn-default' %>
<% end %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @rate } %>

<%= form_for [:admin, @product, @rate] do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/rates/index.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: {current: :rates} %>

<% content_for :page_title do %>
<%= Spree.t(:rate) %>
<% end %>

<% content_for :page_actions do %>
  <span id="new_product_type_link">
      <%= button_link_to Spree.t(:new_rate), new_admin_product_rate_path, { class: "btn-success", icon: 'add', id: 'admin_new_rate_link' }  %>
    </span>
<% end %>

<table class="table" id='listing_rates'>
  <thead>
    <tr data-hook="rate_<%= @product_type_name %>_header">
      <% @product_option_types.each do |option_type| %>
        <th><%= option_type.name %></th>
      <% end %>
      <% @product_rate_option_types.each do |rate_option_type| %>
      <th><%= rate_option_type.presentation %></th>
      <% end %>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @product_rates.each do |rate| %>
    <tr>
      <% @product_option_types.each do |option_type| %>
        <td><%= rate.variant.option_value(option_type.name) %></td>
      <% end %>
      <% @product_rate_option_types.each do |rate_option_type| %>
        <td><%= rate.persisted_option_value(rate_option_type) %></td>
      <% end %>
      <td class="actions">
      <!-- TODO fix bug regarding the links redirecting to some crazy url -->
	      <%= link_to_edit(rate, no_text: true, class: 'admin_edit_rate') %>
	      <%= link_to_delete(rate, no_text: true) %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/rates/new.html.erb
<%#= render :partial => 'spree/admin/shared/product_sub_menu' %>

<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => 'Product Rate'} %>

<% content_for :page_title do %>
  <%= Spree.t(:new_rate) %>
<% end %>

<% content_for :page_actions do %>
  <li><%= link_to_with_icon 'icon-arrow-left', Spree.t(:back_to_rates_list), admin_product_rates_path(@product), :class => 'button' %></li>
<% end %>

<%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @rate } %>

<%= form_for [:admin, @product, @rate] do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>